#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Run lint-staged to run ESLint on staged files
npx lint-staged

# Exit with error if ESLint fails
if [ $? -ne 0 ]; then
  echo "❌ ESLint check failed. Please fix the errors before committing."
  exit 1
fi
